# Change these first
owner: RuaDev # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Acme
    url: https://acme.rua.dev
  - name: API
    url: https://api.rua.dev
  - name: DeepL X
    url: https://deeplx.rua.dev
  - name: Google Gemini Reverse Proxy
    url: https://gemini.rua.dev
  - name: Note
    url: https://note.rua.dev
  - name: Paper Metadata Catch
    url: https://pmd.rua.dev
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.rua.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/RuaDev/upptime/master/assets/logo.png
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
